project:
    type: website
    output-dir: ../

website:
    title: "Scientific Computing in Python"
    sidebar:
        contents: auto
    search: true
    page-navigation: true
    repo-url: https://github.com/cd-public/scicom
    repo-actions: [source, issue]



subtitle: "Scientific Computing"
author: "Prof. Calvin"
  
jupyter: python3

format:
    html:
        theme: darkly 
    revealjs: 
        theme: dark
        mainfont: monospace
        slide-number: true
        show-slide-number: all
        width: 1050
        height: 700
        footer: "[Home](../index.html)"
        output-ext: rjs.html

execute:
    echo: true
    cache: true
    freeze: true  # never re-render during project render