project:
    type: website
    output-dir: ../
    render:
        - index.qmd
        - 01_python.qmd
    
website:
    title: "Scientific Computing in Python"
    

  
format: 
    revealjs: 
        author: "Prof. Calvin"
        subtitle: "Scientific Computing"
        theme: dark
        mainfont: monospace
        slide-number: true
        show-slide-number: all
        width: 1050
        height: 700
        footer: "[Home](../index.html)"
        output-ext: rjs.html
    html:
        theme: Darkly
     
jupyter: python3

execute:
    echo: true
    cache: true
    freeze: true  # never re-render during project render

