project:
  type: website
  output-dir: ../

subtitle: "Scientific Computing"
author: "Prof. Calvin"
  
jupyter: python3

format: 
    revealjs: 
        theme: dark
        mainfont: monospace
        slide-number: true
        show-slide-number: all
        width: 1050
        height: 700
        footer: "[Home](../index.html)"

execute:
    echo: true
    cache: true
    freeze: true  # never re-render during project render
